services:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis

  server:
    build: .
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 3000:3000
    depends_on:
      - redis
